#!/bin/bash
# jq tutorial: https://www.baeldung.com/linux/jq-command-json

# -----------------------------------------------------
# Variables
# -----------------------------------------------------
name="Packages Installer Script"
title=""
description=""
distribution=""
successmessage=""
json=""

# -----------------------------------------------------
# Load Configuration
# -----------------------------------------------------
_loadConfiguration() {
	file=$1
	_loadFromFile $file
}

# -----------------------------------------------------
# Load Configuration from file
# -----------------------------------------------------
_loadFromFile() {
    file=$1
    if [ ! -f $file ]; then
		exit
    fi
    json=$(cat $file)
	_showHeader
    _runInstallation
}

# -----------------------------------------------------
# Load Configuration from remote
# -----------------------------------------------------
_loadFromRemote() {
    echo "Loading from Remote"
}

# -----------------------------------------------------
# Run the installation
# -----------------------------------------------------
_showHeader() {
    title=$(echo $json | jq -r '.title')
    description=$(echo $json | jq -r '.description')
    distribution=$(echo $json | jq -r '.distribution')
    successmessage=$(echo $json | jq -r '.successmessage')

    echo $title
    echo "---------------------------------------------------"
    echo $description
    echo
}

# -----------------------------------------------------
# Run the installation
# -----------------------------------------------------
_runInstallation() {
    sudo -v
    l=$(echo $json | jq '.packages | length')
    for ((i=0; i<$l; i++)); do
        package=$(echo $json | jq -r '.packages['$i'].package')
        description=$(echo $json | jq -r '.packages['$i'].description')
        installationcommand=$(echo $json | jq -r '.packages['$i'].installationcommand')

        echo "Installing $package ..."
        if [[ ! -z $description ]] && [[ ! $description == "null" ]]; then
            echo $description
        fi

        _installPackage "$installationcommand" "$package"
        echo
    done
}

# -----------------------------------------------------
# Install Package
# -----------------------------------------------------
_installPackage() {
    installationcommand="$1"
    package="$2"
    [[ $(_isInstalled "$package") == "0" ]] && echo "$package is already installed" || eval "$installationcommand $package"
}

# ------------------------------------------------------
# Is package installed?
# ------------------------------------------------------
_isInstalled() {
    package="$1"
    case $distribution in
        arch)
            check="$(sudo pacman -Qs --color always "${package}" | grep "local" | grep "${package} ")"
            [ -n "${check}" ] && echo "0" || echo "1"
        ;;
        fedora)
            check=$(dnf list --installed | grep $package)
            [ -n "${check}" ] && echo "0" || echo "1"
        ;;
        opensuse)
			echo 1
        ;;
        *)
			echo 1
        ;;
    esac
}

# -----------------------------------------------------
# Manage Parameters
# -----------------------------------------------------
while getopts ":h:" opt; do
    case $opt in
        h)
            echo ":: Packages Installer Script"
            exit
        ;;
    esac
done

[ ! -z $1 ] && _loadConfiguration "$1" || exit
