#!/usr/bin/env bash

#    ___           __                       ____         __       ____
#   / _ \___ _____/ /_____ ____ ____ ___   /  _/__  ___ / /____ _/ / /__ ____
#  / ___/ _ `/ __/  '_/ _ `/ _ `/ -_|_-<  _/ // _ \(_-</ __/ _ `/ / / -_) __/
# /_/   \_,_/\__/_/\_\\_,_/\_, /\__/___/ /___/_//_/___/\__/\_,_/_/_/\__/_/
#                         /___/
# Version 1.0
# By Stephan Raabe

pkginst_script_folder="$HOME/.local/share/com.ml4w.packagesinstaller"

# ------------------------------------------------
# Prepare the application
# ------------------------------------------------
source "$pkginst_script_folder/modules/application.sh"

# ------------------------------------------------
# Sudo Login
# ------------------------------------------------
source "$pkginst_script_folder/modules/sudo.sh"

# ------------------------------------------------
# Install Dependencies
# ------------------------------------------------
source "$pkginst_script_folder/modules/dependencies.sh"

# ------------------------------------------------
# Load Package Configuration
# ------------------------------------------------
source "$pkginst_script_folder/modules/configuration.sh"

# ------------------------------------------------
# Confirmation
# ------------------------------------------------
source "$pkginst_script_folder/modules/confirmation.sh"

# ------------------------------------------------
# Pre Script
# ------------------------------------------------
source "$pkginst_script_folder/modules/pre.sh"

# ------------------------------------------------
# Installation of Packages
# ------------------------------------------------
source "$pkginst_script_folder/modules/packages.sh"

# ------------------------------------------------
# Post Script
# ------------------------------------------------
source "$pkginst_script_folder/modules/post.sh"

# ------------------------------------------------
# Reboot
# ------------------------------------------------
source "$pkginst_script_folder/modules/reboot.sh"